### ISSUE TITLE
Implement Fr

### ISSUE THREAD

**Issue by mallochine** [herumi/bls-wasm#10]
Need to implement JS equivalent of Fr interface

It is implemented in Go here: https://github.com/herumi/bls-go-binary/blob/53088ea089c79aa79e23fceae1514daa4b1a98d7/bls/mcl.go#L134

**Comment by herumi** [comment]
add `Fr` class.
https://github.com/herumi/bls-wasm/blob/master/test/mcl-test.js#L24
