### ISSUE TITLE
Implement SetRandFunc interface

### ISSUE THREAD

**Issue by mallochine** [herumi/bls-wasm#9]
Hello,

Need to implement JS equivalent interface call of `bls.SetRandfunc`

Golang has it implemented here: https://github.com/herumi/bls-go-binary/blob/54b1b8877712a3ac8e6213b31351a736ad3aa6b1/bls/bls.go#L730

**Comment by herumi** [comment]
Please use `bls.setRandFunc`.
https://github.com/herumi/bls-wasm/blob/master/src/bls.js#L760
